name: Build and Deploy Smotrilka Web

on:
  push:
    branches:
      - reboot

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set IMAGE name
        run: echo "IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/smotrilka-web-v2" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd Smotrilka-Web
          VERSION=$(date +%Y.%m.%d.%H%M)
          docker build . -t $IMAGE:latest -t $IMAGE:$VERSION
          docker push $IMAGE:latest
          docker push $IMAGE:$VERSION

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/smotrilka-web-v2
            docker pull $IMAGE:latest
            docker stop smotrilka-web-v2 || true
            docker rm smotrilka-web-v2 || true

            docker run -d \
              --name smotrilka-web-v2 \
              --restart=always \
              -p 10001:10000 \
              $IMAGE:latest
